name: CI-Build

on:
  push:
    branches:
      - "main"
    paths:
      - "customer-api-provider/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "customer-api-provider/**"
      - ".github/workflows/ci.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: "mvn -B package --file pom.xml"
        working-directory: "./customer-api-provider"
